### ISSUE TITLE
Data issue not found?

### ISSUE THREAD

**Issue by dopple6661** [princefr/Fuse.Signature#2]
I'm having a little problem using this on Fuse. I keep getting "{data} not found in data context" on this downloaded file. I can't draw on it as is either.

In my own project I integrated this into I get the error: Data type not found: Native.Signature

**Comment by princefr** [comment]
Can you share your code  and what you attempted so it will be much easier to help you.
the module only works on real devices.

**Comment by princefr** [comment]
seems like you runned the module on the preview mode and not on devices as said on the documentation. i'm closing this. please open if needed.

**Comment by dopple6661** [comment]
My fault! Syntax error! Thank you! This works amazing!
